// app/reports.tsx
import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Platform, Alert, ActivityIndicator } from 'react-native';
import { useSafeAreaBottomPadding } from '../src/hooks/useTabBarHeight';
import { useRouter } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import { ArrowLeft, TrendingUp, CreditCard, ArrowDownLeft, FileSpreadsheet, FileDown } from 'lucide-react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { useTheme } from '../src/contexts/ThemeContext';
import { type AppColors, Spacing, FontSize, FontWeight, BorderRadius, Shadow } from '../src/constants/theme';
import { useAuth } from '../src/contexts/AuthContext';
import { useShop } from '../src/contexts/ShopContext';
import { reportService, ReportPeriod } from '../src/services/database/reportService';
import { CURRENCY_SYMBOL } from '../src/constants';

const PERIODS: { label: string; value: ReportPeriod }[] = [
  { label: 'Today', value: 'today' },
  { label: 'Yesterday', value: 'yesterday' },
  { label: 'This Week', value: 'week' },
  { label: 'This Month', value: 'month' },
  { label: 'Last Month', value: 'lastMonth' },
  { label: 'This Year', value: 'year' },
];

export function ReportsScreen() {
  const { t } = useTranslation();
  const router = useRouter();
  const { shopId } = useAuth();
  const { shop } = useShop();
  const { colors } = useTheme();

  const [period, setPeriod] = useState<ReportPeriod>('month');
  const [exporting, setExporting] = useState(false);
  const bottomPadding = useSafeAreaBottomPadding(Spacing.base);

  const { data: report, isLoading, refetch } = useQuery({
    queryKey: ['report-data', shopId, period],
    queryFn: () => reportService.getFullReport(shopId || '', period),
    enabled: !!shopId,
  });

  const handleExportPDF = async () => {
    if (!report || !shop) return;
    setExporting(true);
    try {
      const gstRows = report.gstSummary.map(row => `
        <tr>
          <td>GST @ ${row.rate}%</td>
          <td style="text-align:right">${CURRENCY_SYMBOL}${row.taxable.toFixed(2)}</td>
          <td style="text-align:right">${CURRENCY_SYMBOL}${row.tax.toFixed(2)}</td>
        </tr>
      `).join('');

      const paymentRows = Object.entries(report.paymentByMethod).map(([method, val]) => `
        <tr>
          <td style="text-transform:capitalize">${method}</td>
          <td style="text-align:right">${CURRENCY_SYMBOL}${val.toFixed(2)}</td>
        </tr>
      `).join('');

      const customerRows = report.topCustomers.map((c, i) => `
        <tr>
          <td>${i + 1}</td>
          <td>${c.name}</td>
          <td style="text-align:right">${CURRENCY_SYMBOL}${c.total.toFixed(2)}</td>
          <td style="text-align:right">${CURRENCY_SYMBOL}${c.outstanding.toFixed(2)}</td>
        </tr>
      `).join('');

      const html = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: sans-serif; padding: 20px; color: #333; }
    h1 { color: #1B5E20; margin-bottom: 5px; }
    .header-sub { font-size: 14px; color: #666; margin-bottom: 20px; }
    .kpi-container { display: flex; gap: 10px; margin-bottom: 20px; }
    .kpi-card { flex: 1; border: 1px solid #ddd; border-radius: 8px; padding: 12px; background: #fdfdfd; }
    .kpi-title { font-size: 11px; text-transform: uppercase; color: #888; }
    .kpi-value { font-size: 16px; font-weight: bold; margin-top: 4px; color: #111; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 25px; }
    th { background: #1B5E20; color: white; text-align: left; padding: 8px; font-size: 12px; }
    td { border-bottom: 1px solid #eee; padding: 8px; font-size: 12px; }
    .section-title { color: #1B5E20; border-bottom: 2px solid #1B5E20; padding-bottom: 4px; margin-top: 25px; margin-bottom: 10px; font-size: 14px; font-weight: bold; }
  </style>
</head>
<body>
  <h1>${shop.shopName} — ${t('reports.businessSummary', 'Business Summary Report')}</h1>
  <div class="header-sub">${t('reports.range', 'Period')}: ${report.period} | ${t('reports.generatedBy', 'Generated by')} ${t('common.appName', 'BillDesk')}</div>

  <div class="kpi-container">
    <div class="kpi-card">
      <div class="kpi-title">${t('reports.totalSales', 'Total Sales')}</div>
      <div class="kpi-value">${CURRENCY_SYMBOL}${report.totalSales.toFixed(2)}</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-title">${t('reports.totalCollected', 'Total Received')}</div>
      <div class="kpi-value" style="color:green">${CURRENCY_SYMBOL}${report.totalReceived.toFixed(2)}</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-title">${t('reports.totalOutstanding', 'Outstanding')}</div>
      <div class="kpi-value" style="color:red">${CURRENCY_SYMBOL}${report.totalOutstanding.toFixed(2)}</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-title">${t('invoices.title', 'Total Invoices')}</div>
      <div class="kpi-value">${report.totalInvoices}</div>
    </div>
  </div>

  ${gstRows ? `
  <div class="section-title">${t('reports.gstSummary', 'GST Tax Summary')}</div>
  <table>
    <thead>
      <tr><th>${t('reports.gstSlab', 'GST Slab')}</th><th style="text-align:right">${t('reports.taxableAmt', 'Taxable Value')}</th><th style="text-align:right">${t('reports.taxAmt', 'Tax Amount')}</th></tr>
    </thead>
    <tbody>${gstRows}</tbody>
  </table>` : ''}

  ${paymentRows ? `
  <div class="section-title">${t('reports.collectionsByMethod', 'Payment Method Breakdown')}</div>
  <table>
    <thead>
      <tr><th>${t('payments.method', 'Method')}</th><th style="text-align:right">${t('reports.totalCollected', 'Amount Collected')}</th></tr>
    </thead>
    <tbody>${paymentRows}</tbody>
  </table>` : ''}

  ${customerRows ? `
  <div class="section-title">${t('reports.topCustomers', 'Top Customers by Sales')}</div>
  <table>
    <thead>
      <tr><th>#</th><th>${t('customers.name', 'Customer Name')}</th><th style="text-align:right">${t('customers.totalBilled', 'Total Billed')}</th><th style="text-align:right">${t('customers.outstanding', 'Outstanding')}</th></tr>
    </thead>
    <tbody>${customerRows}</tbody>
  </table>` : ''}
</body>
</html>`;

      const { uri } = await Print.printToFileAsync({ html });
      const fileName = `Report_${period}_${Date.now()}.pdf`;
      const destUri = `${FileSystem.documentDirectory}${fileName}`;
      await FileSystem.moveAsync({ from: uri, to: destUri });

      const isAvailable = await Sharing.isAvailableAsync();
      if (isAvailable) {
        await Sharing.shareAsync(destUri);
      } else {
        Alert.alert(t('reports.reportSaved', 'Report Saved'), `Saved to documents folder: ${fileName}`);
      }
    } catch (e) {
      console.error(e);
      Alert.alert(t('common.failed', 'Failed'), t('reports.failedExport', 'Failed to export report PDF'));
    } finally {
      setExporting(false);
    }
  };

  const styles = getStyles(colors);

  return (
    <View style={styles.container}>
      {/* Top Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
          <ArrowLeft size={20} color={colors.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>{t('reports.title', 'Business Reports')}</Text>
        <TouchableOpacity onPress={handleExportPDF} disabled={exporting || isLoading} style={styles.exportBtn}>
          {exporting ? <ActivityIndicator size="small" color={colors.primary} /> : <FileDown size={20} color={colors.primary} />}
        </TouchableOpacity>
      </View>

      {/* Select Period Chips */}
      <View style={{ backgroundColor: colors.surface }}>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.periodRow}>
          {PERIODS.map(p => (
            <TouchableOpacity
              key={p.value}
              style={[styles.periodChip, period === p.value && styles.periodChipActive]}
              onPress={() => setPeriod(p.value)}
            >
              <Text style={[styles.periodText, period === p.value && styles.periodTextActive]}>
                {p.value === 'today' ? t('dashboard.today') : p.value === 'week' ? t('dashboard.week') : p.value === 'month' ? t('dashboard.month') : p.value === 'year' ? t('dashboard.year') : t(`reports.${p.value}`)}
              </Text>
            </TouchableOpacity>
          ))}
        </ScrollView>
      </View>

      {isLoading ? (
        <View style={styles.center}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={{ marginTop: Spacing.base, color: colors.textSecondary }}>{t('reports.aggregating', 'Aggregating financials...')}</Text>
        </View>
      ) : !report ? (
        <View style={styles.center}>
          <Text style={{ color: colors.textSecondary }}>{t('reports.noData', 'No data found for this period.')}</Text>
        </View>
      ) : (
        <ScrollView contentContainerStyle={[styles.scrollContent, { paddingBottom: bottomPadding }]} showsVerticalScrollIndicator={false}>
          
          <Text style={styles.periodLabel}>{t('reports.range', 'Report range')}: {report.period}</Text>

          {/* Stats Cards */}
          <View style={styles.kpiGrid}>
            <View style={styles.kpiRow}>
              <View style={styles.kpiCard}>
                <TrendingUp size={20} color={colors.primary} />
                <Text style={styles.kpiTitle}>{t('reports.totalSales', 'Total Sales')}</Text>
                <Text style={styles.kpiValue}>{CURRENCY_SYMBOL}{report.totalSales.toLocaleString('en-IN')}</Text>
              </View>
              <View style={styles.kpiCard}>
                <ArrowDownLeft size={20} color={colors.success} />
                <Text style={styles.kpiTitle}>{t('reports.totalCollected', 'Total Received')}</Text>
                <Text style={[styles.kpiValue, { color: colors.success }]}>{CURRENCY_SYMBOL}{report.totalReceived.toLocaleString('en-IN')}</Text>
              </View>
            </View>

            <View style={styles.kpiRow}>
              <View style={styles.kpiCard}>
                <CreditCard size={20} color={colors.error} />
                <Text style={styles.kpiTitle}>{t('reports.totalOutstanding', 'Total Outstanding')}</Text>
                <Text style={[styles.kpiValue, { color: colors.error }]}>{CURRENCY_SYMBOL}{report.totalOutstanding.toLocaleString('en-IN')}</Text>
              </View>
              <View style={styles.kpiCard}>
                <FileSpreadsheet size={20} color={colors.info} />
                <Text style={styles.kpiTitle}>{t('invoices.title', 'Total Invoices')}</Text>
                <Text style={styles.kpiValue}>{report.totalInvoices}</Text>
              </View>
            </View>
          </View>

          {/* GST Summary Table */}
          <View style={styles.tableCard}>
            <Text style={styles.cardHeaderTitle}>{t('reports.gstSummary', 'GST Tax Summary')}</Text>
            {report.gstSummary.length === 0 ? (
              <Text style={styles.emptyText}>{t('reports.noTaxCalculations', 'No tax calculations for this period')}</Text>
            ) : (
              <View>
                <View style={styles.tableHead}>
                  <Text style={[styles.headCol, { flex: 1 }]}>{t('reports.gstSlab', 'GST Slab')}</Text>
                  <Text style={[styles.headCol, { textAlign: 'right', flex: 1.5 }]}>{t('reports.taxableAmt', 'Taxable Amt')}</Text>
                  <Text style={[styles.headCol, { textAlign: 'right', flex: 1.5 }]}>{t('reports.taxAmt', 'Tax Amt')}</Text>
                </View>
                {report.gstSummary.map((item, idx) => (
                  <View key={idx} style={styles.tableRow}>
                    <Text style={[styles.rowCol, { flex: 1, fontWeight: 'bold' }]}>GST @ {item.rate}%</Text>
                    <Text style={[styles.rowCol, { textAlign: 'right', flex: 1.5 }]}>{CURRENCY_SYMBOL}{item.taxable.toFixed(2)}</Text>
                    <Text style={[styles.rowCol, { textAlign: 'right', flex: 1.5, color: colors.primary, fontWeight: 'bold' }]}>{CURRENCY_SYMBOL}{item.tax.toFixed(2)}</Text>
                  </View>
                ))}
              </View>
            )}
          </View>

          {/* Payments by Method */}
          <View style={styles.tableCard}>
            <Text style={styles.cardHeaderTitle}>{t('reports.collectionsByMethod', 'Collections By Method')}</Text>
            {Object.keys(report.paymentByMethod).length === 0 ? (
              <Text style={styles.emptyText}>{t('reports.noPayments', 'No payments recorded in this period')}</Text>
            ) : (
              <View>
                <View style={styles.tableHead}>
                  <Text style={[styles.headCol, { flex: 2 }]}>{t('payments.method', 'Payment Method')}</Text>
                  <Text style={[styles.headCol, { textAlign: 'right', flex: 2 }]}>{t('reports.totalCollected', 'Total Collected')}</Text>
                </View>
                {Object.entries(report.paymentByMethod).map(([method, val]) => (
                  <View key={method} style={styles.tableRow}>
                    <Text style={[styles.rowCol, { flex: 2, textTransform: 'capitalize', fontWeight: '500' }]}>{method}</Text>
                    <Text style={[styles.rowCol, { textAlign: 'right', flex: 2, color: colors.success, fontWeight: 'bold' }]}>{CURRENCY_SYMBOL}{val.toFixed(2)}</Text>
                  </View>
                ))}
              </View>
            )}
          </View>

          {/* Top Customers */}
          <View style={styles.tableCard}>
            <Text style={styles.cardHeaderTitle}>{t('reports.topCustomers', 'Top Billing Customers')}</Text>
            {report.topCustomers.length === 0 ? (
              <Text style={styles.emptyText}>{t('reports.noCustomerSales', 'No customer sales in this period')}</Text>
            ) : (
              <View>
                <View style={styles.tableHead}>
                  <Text style={[styles.headCol, { flex: 2 }]}>{t('invoices.customer', 'Customer')}</Text>
                  <Text style={[styles.headCol, { textAlign: 'right', flex: 1.5 }]}>{t('customers.totalBilled', 'Total Billed')}</Text>
                  <Text style={[styles.headCol, { textAlign: 'right', flex: 1.5 }]}>{t('customers.outstanding', 'Outstanding')}</Text>
                </View>
                {report.topCustomers.map((cust, idx) => (
                  <View key={idx} style={styles.tableRow}>
                    <Text style={[styles.rowCol, { flex: 2 }]} numberOfLines={1}>{cust.name}</Text>
                    <Text style={[styles.rowCol, { textAlign: 'right', flex: 1.5 }]}>{CURRENCY_SYMBOL}{cust.total.toFixed(0)}</Text>
                    <Text style={[styles.rowCol, { textAlign: 'right', flex: 1.5, color: cust.outstanding > 0 ? colors.error : colors.success }]}>
                      {CURRENCY_SYMBOL}{cust.outstanding.toFixed(0)}
                    </Text>
                  </View>
                ))}
              </View>
            )}
          </View>

        </ScrollView>
      )}
    </View>
  );
}

const getStyles = (colors: AppColors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    marginTop: Platform.OS === 'ios' ? 50 : 30,
    paddingHorizontal: Spacing.base, paddingVertical: Spacing.sm,
    backgroundColor: colors.surface, borderBottomWidth: 1, borderColor: colors.border,
  },
  backButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  headerTitle: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: colors.textPrimary },
  exportBtn: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  periodRow: { paddingHorizontal: Spacing.base, paddingVertical: 10, gap: Spacing.sm },
  periodChip: { paddingHorizontal: Spacing.base, paddingVertical: 7, borderRadius: BorderRadius.full, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  periodChipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  periodText: { fontSize: FontSize.sm, color: colors.textSecondary, fontWeight: FontWeight.semibold },
  periodTextActive: { color: '#FFFFFF' },
  scrollContent: { padding: Spacing.base },
  periodLabel: { fontSize: FontSize.xs, color: colors.textSecondary, fontWeight: FontWeight.semibold, marginBottom: Spacing.base },
  kpiGrid: { gap: Spacing.sm, marginBottom: Spacing.base },
  kpiRow: { flexDirection: 'row', gap: Spacing.sm },
  kpiCard: {
    flex: 1, backgroundColor: colors.surface, borderRadius: BorderRadius.lg,
    borderWidth: 1, borderColor: colors.border, padding: Spacing.base, ...Shadow.sm,
  },
  kpiTitle: { fontSize: FontSize.xs, color: colors.textSecondary, marginTop: 6 },
  kpiValue: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: colors.textPrimary, marginTop: 2 },
  tableCard: {
    backgroundColor: colors.surface, borderRadius: BorderRadius.xl,
    padding: Spacing.base, borderWidth: 1, borderColor: colors.border,
    ...Shadow.sm, marginBottom: Spacing.base,
  },
  cardHeaderTitle: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: colors.textPrimary, marginBottom: Spacing.base },
  emptyText: { fontSize: FontSize.xs, color: colors.textDisabled, textAlign: 'center', paddingVertical: Spacing.base },
  tableHead: { flexDirection: 'row', paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: colors.border },
  headCol: { fontSize: FontSize.xs, fontWeight: FontWeight.bold, color: colors.textSecondary },
  tableRow: { flexDirection: 'row', paddingVertical: 10, borderBottomWidth: 0.5, borderBottomColor: colors.divider, alignItems: 'center' },
  rowCol: { fontSize: FontSize.sm, color: colors.textPrimary },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: Spacing.xl },
});

export default function wrapper() {
  return <ReportsScreen />;
}
